import { Video } from "../vite-env";

export const mediaList: Video[] = [
    {
        _id: "1",
        image: "https://example.com/image1.jpg",
        type: "film",
        title: "The Shining",
        description: "A family heads to an isolated hotel where a sinister presence influences the father into violence.",
        date: "1980-05-23",
        rating: 8.4,
        chapters: [],
        tags: ["Terror", "Suspenso", "Psicológico"]
    },
    {
        _id: "2",
        image: "https://example.com/image2.jpg",
        type: "serie",
        title: "Stranger Things",
        description: "A group of kids uncover a series of supernatural mysteries in their small town.",
        date: "2016-07-15",
        rating: 8.7,
        chapters: [],
        tags: ["Terror", "Ciencia Ficción", "Aventura"]
    },
    {
        _id: "3",
        image: "https://example.com/image3.jpg",
        type: "film",
        title: "A Quiet Place",
        description: "A family must live in silence to avoid mysterious creatures that hunt by sound.",
        date: "2018-04-06",
        rating: 7.5,
        chapters: [],
        tags: ["Terror", "Suspenso", "Drama"]
    },
    {
        _id: "4",
        image: "https://example.com/image4.jpg",
        type: "film",
        title: "Moana",
        description: "A daring young girl sets out on a seafaring journey to save her island.",
        date: "2016-11-23",
        rating: 7.6,
        chapters: [],
        tags: ["Familia", "Aventura", "Animación"]
    },
    {
        _id: "5",
        image: "https://example.com/image5.jpg",
        type: "film",
        title: "Avengers: Endgame",
        description: "The remaining Avengers must find a way to bring back their vanquished allies to stop Thanos.",
        date: "2019-04-26",
        rating: 8.4,
        chapters: [],
        tags: ["Acción", "Ciencia Ficción", "Superhéroes"]
    },
    {
        _id: "6",
        image: "https://example.com/image6.jpg",
        type: "serie",
        title: "Breaking Bad",
        description: "A high school chemistry teacher turned methamphetamine manufacturer faces moral consequences.",
        date: "2008-01-20",
        rating: 9.5,
        chapters: [],
        tags: ["Drama", "Crimen", "Suspenso"]
    },
    {
        _id: "7",
        image: "https://example.com/image7.jpg",
        type: "film",
        title: "The Godfather",
        description: "The aging patriarch of an organized crime dynasty transfers control to his reluctant son.",
        date: "1972-03-24",
        rating: 9.2,
        chapters: [],
        tags: ["Crimen", "Drama", "Suspenso"]
    },
    {
        _id: "8",
        image: "https://example.com/image8.jpg",
        type: "serie",
        title: "The Crown",
        description: "Follows the political rivalries and romance of Queen Elizabeth II's reign.",
        date: "2016-11-04",
        rating: 8.6,
        chapters: [],
        tags: ["Drama", "Histórico", "Política"]
    },
    {
        _id: "9",
        image: "https://example.com/image9.jpg",
        type: "film",
        title: "Titanic",
        description: "A love story unfolds between Jack and Rose aboard the ill-fated RMS Titanic.",
        date: "1997-12-19",
        rating: 7.8,
        chapters: [],
        tags: ["Romance", "Drama", "Histórico"]
    },
    {
        _id: "10",
        image: "https://example.com/image10.jpg",
        type: "film",
        title: "Jurassic Park",
        description: "A theme park populated by cloned dinosaurs faces disaster when the creatures break loose.",
        date: "1993-06-11",
        rating: 8.1,
        chapters: [],
        tags: ["Ciencia Ficción", "Aventura", "Acción"]
    },
    {
        _id: "11",
        image: "https://example.com/image11.jpg",
        type: "serie",
        title: "Friends",
        description: "Follows the personal and professional lives of six friends living in Manhattan.",
        date: "1994-09-22",
        rating: 8.9,
        chapters: [],
        tags: ["Comedia", "Romance", "Familia"]
    },
    {
        _id: "12",
        image: "https://example.com/image12.jpg",
        type: "film",
        title: "Inception",
        description: "A skilled thief uses dream-sharing technology to steal secrets from people's minds.",
        date: "2010-07-16",
        rating: 8.8,
        chapters: [],
        tags: ["Ciencia Ficción", "Acción", "Suspenso"]
    },
    {
        _id: "13",
        image: "https://example.com/image13.jpg",
        type: "film",
        title: "Toy Story",
        description: "A group of toys come to life when their owner is not around, embarking on adventures together.",
        date: "1995-11-22",
        rating: 8.3,
        chapters: [],
        tags: ["Animación", "Familia", "Aventura"]
    },
    {
        _id: "14",
        image: "https://example.com/image14.jpg",
        type: "film",
        title: "Get Out",
        description: "A young African-American man uncovers disturbing secrets when visiting his white girlfriend's family.",
        date: "2017-02-24",
        rating: 7.7,
        chapters: [],
        tags: ["Terror", "Suspenso", "Misterio"]
    },
    {
        _id: "15",
        image: "https://example.com/image15.jpg",
        type: "film",
        title: "The Lion King",
        description: "A young lion prince flees his kingdom after the murder of his father and returns to reclaim his throne.",
        date: "1994-06-15",
        rating: 8.5,
        chapters: [],
        tags: ["Animación", "Familia", "Aventura"]
    },
    {
        _id: "16",
        image: "https://example.com/image16.jpg",
        type: "film",
        title: "Mad Max: Fury Road",
        description: "In a post-apocalyptic wasteland, a drifter and a rebel warrior join forces to overthrow a tyrant.",
        date: "2015-05-15",
        rating: 8.1,
        chapters: [],
        tags: ["Acción", "Aventura", "Ciencia Ficción"]
    },
    {
        _id: "17",
        image: "https://example.com/image17.jpg",
        type: "serie",
        title: "The Mandalorian",
        description: "A lone bounty hunter travels the galaxy, protecting a mysterious child from those who seek to exploit it.",
        date: "2019-11-12",
        rating: 8.7,
        chapters: [],
        tags: ["Ciencia Ficción", "Acción", "Aventura"]
    },
    {
        _id: "18",
        image: "https://example.com/image18.jpg",
        type: "film",
        title: "The Matrix",
        description: "A hacker discovers the world he lives in is a simulated reality and joins a rebellion to break free.",
        date: "1999-03-31",
        rating: 8.7,
        chapters: [],
        tags: ["Ciencia Ficción", "Acción", "Suspenso"]
    },
    {
        _id: "19",
        image: "https://example.com/image19.jpg",
        type: "serie",
        title: "The Witcher",
        description: "A mutated monster-hunter struggles to find his place in a world where people often prove more wicked than beasts.",
        date: "2019-12-20",
        rating: 8.2,
        chapters: [],
        tags: ["Fantasía", "Acción", "Aventura"]
    },
    {
        _id: "20",
        image: "https://example.com/image20.jpg",
        type: "film",
        title: "Black Panther",
        description: "T'Challa, the King of Wakanda, rises to the throne in the isolated, technologically advanced African nation.",
        date: "2018-02-16",
        rating: 7.3,
        chapters: [],
        tags: ["Acción", "Ciencia Ficción", "Superhéroes"]
    },
    {
        _id: "21",
        image: "https://example.com/image21.jpg",
        type: "serie",
        title: "Game of Thrones",
        description: "Noble families vie for control of the Iron Throne in the Seven Kingdoms of Westeros.",
        date: "2011-04-17",
        rating: 9.2,
        chapters: [],
        tags: ["Fantasía", "Acción", "Drama"]
    },
    {
        _id: "22",
        image: "https://example.com/image22.jpg",
        type: "film",
        title: "The Dark Knight",
        description: "Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
        date: "2008-07-18",
        rating: 9.0,
        chapters: [],
        tags: ["Acción", "Crimen", "Superhéroes"]
    },
    {
        _id: "23",
        image: "https://example.com/image23.jpg",
        type: "film",
        title: "Pulp Fiction",
        description: "The lives of two mob hitmen, a boxer, a gangster, and his wife intertwine in four tales of violence and redemption.",
        date: "1994-10-14",
        rating: 8.9,
        chapters: [],
        tags: ["Crimen", "Drama", "Suspenso"]
    },
    {
        _id: "24",
        image: "https://example.com/image24.jpg",
        type: "serie",
        title: "Narcos",
        description: "A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar and the Medellín Cartel.",
        date: "2015-08-28",
        rating: 8.8,
        chapters: [],
        tags: ["Crimen", "Drama", "Histórico"]
    },
    {
        _id: "25",
        image: "https://example.com/image25.jpg",
        type: "film",
        title: "La La Land",
        description: "A jazz musician and an aspiring actress meet and fall in love while pursuing their dreams in Los Angeles.",
        date: "2016-12-09",
        rating: 8.0,
        chapters: [],
        tags: ["Romance", "Musical", "Drama"]
    },
    {
        _id: "26",
        image: "https://example.com/image26.jpg",
        type: "film",
        title: "Gone Girl",
        description: "A husband becomes the focus of an intense media circus when his wife disappears, and all signs point to him.",
        date: "2014-10-03",
        rating: 8.1,
        chapters: [],
        tags: ["Suspenso", "Drama", "Misterio"]
    },
    {
        _id: "27",
        image: "https://example.com/image27.jpg",
        type: "serie",
        title: "The Office",
        description: "A mockumentary on a group of typical office workers, where the workday consists of ego clashes and inappropriate behavior.",
        date: "2005-03-24",
        rating: 8.9,
        chapters: [],
        tags: ["Comedia", "Familia"]
    },
    {
        _id: "28",
        image: "https://example.com/image28.jpg",
        type: "film",
        title: "The Sixth Sense",
        description: "A young boy who communicates with spirits seeks the help of a disheartened child psychologist.",
        date: "1999-08-06",
        rating: 8.1,
        chapters: [],
        tags: ["Terror", "Suspenso", "Drama"]
    },
    {
        _id: "29",
        image: "https://example.com/image29.jpg",
        type: "serie",
        title: "Sherlock",
        description: "A modern update finds the famous sleuth and his doctor partner solving crime in 21st century London.",
        date: "2010-07-25",
        rating: 9.1,
        chapters: [],
        tags: ["Suspenso", "Misterio", "Drama"]
    },
    {
        _id: "30",
        image: "https://example.com/image30.jpg",
        type: "film",
        title: "Forrest Gump",
        description: "The story of Forrest Gump, a man with a low IQ, who unwittingly influences historical events.",
        date: "1994-07-06",
        rating: 8.8,
        chapters: [],
        tags: ["Drama", "Romance", "Histórico"]
    }
];
