import { VideoList } from "../vite-env";

export const series: VideoList[] = [
    // Temática: Terror
    {
        title: "Terror",
        list: [
            {
                _id: "1",
                image: "https://example.com/image1.jpg",
                type: "film",
                title: "The Conjuring",
                description: "Paranormal investigators Ed and Lorraine Warren help a family terrorized by a dark presence.",
                date: "2013-07-19",
                rating: 7.5,
                chapters: [],
            },
            {
                _id: "2",
                image: "https://example.com/image2.jpg",
                type: "film",
                title: "Hereditary",
                description: "A grieving family is haunted by tragic and disturbing occurrences.",
                date: "2018-06-08",
                rating: 7.3,
                chapters: [],
            },
            {
                _id: "3",
                image: "https://example.com/image3.jpg",
                type: "film",
                title: "It",
                description: "A group of bullied kids band together to fight a shape-shifting monster taking the form of a clown.",
                date: "2017-09-08",
                rating: 7.4,
                chapters: [],
            },
            {
                _id: "4",
                image: "https://example.com/image4.jpg",
                type: "serie",
                title: "The Haunting of Hill House",
                description: "A family confronts haunting memories of their old home.",
                date: "2018-10-12",
                rating: 8.6,
                chapters: [],
            },
            {
                _id: "5",
                image: "https://example.com/image5.jpg",
                type: "film",
                title: "Sinister",
                description: "A true-crime writer discovers a box of home movies depicting gruesome murders.",
                date: "2012-10-12",
                rating: 6.8,
                chapters: [],
            },
            {
                _id: "6",
                image: "https://example.com/image6.jpg",
                type: "film",
                title: "The Babadook",
                description: "A troubled widow discovers a mysterious children's book that manifests a sinister presence.",
                date: "2014-11-28",
                rating: 6.9,
                chapters: [],
            },
            {
                _id: "7",
                image: "https://example.com/image7.jpg",
                type: "film",
                title: "A Quiet Place",
                description: "A family must live in silence to avoid mysterious creatures that hunt by sound.",
                date: "2018-04-06",
                rating: 7.5,
                chapters: [],
            },
            {
                _id: "8",
                image: "https://example.com/image8.jpg",
                type: "film",
                title: "Get Out",
                description: "A young African-American visits his white girlfriend's mysterious family estate.",
                date: "2017-02-24",
                rating: 7.7,
                chapters: [],
            },
            {
                _id: "9",
                image: "https://example.com/image9.jpg",
                type: "serie",
                title: "American Horror Story",
                description: "An anthology series exploring various horror themes each season.",
                date: "2011-10-05",
                rating: 8.0,
                chapters: [],
            },
            {
                _id: "10",
                image: "https://example.com/image10.jpg",
                type: "film",
                title: "The Ring",
                description: "A journalist investigates a cursed videotape that kills anyone who watches it.",
                date: "2002-10-18",
                rating: 7.1,
                chapters: [],
            },
            {
                _id: "11",
                image: "https://example.com/image11.jpg",
                type: "film",
                title: "Midsommar",
                description: "A couple travels to a remote Swedish village for a midsummer festival, where they encounter strange rituals.",
                date: "2019-07-03",
                rating: 7.1,
                chapters: [],
            },
            {
                _id: "12",
                image: "https://example.com/image12.jpg",
                type: "film",
                title: "The Witch",
                description: "A Puritan family encounters dark forces in the woods surrounding their isolated home.",
                date: "2015-02-19",
                rating: 6.9,
                chapters: [],
            },
            {
                _id: "13",
                image: "https://example.com/image13.jpg",
                type: "film",
                title: "The Exorcist",
                description: "A mother seeks the help of two priests to save her daughter from demonic possession.",
                date: "1973-12-26",
                rating: 8.0,
                chapters: [],
            },
            {
                _id: "14",
                image: "https://example.com/image14.jpg",
                type: "film",
                title: "Psycho",
                description: "A woman on the run takes refuge at a secluded motel run by a troubled young man.",
                date: "1960-09-08",
                rating: 8.5,
                chapters: [],
            },
            {
                _id: "15",
                image: "https://example.com/image15.jpg",
                type: "film",
                title: "Saw",
                description: "Two men awaken in a grimy, abandoned bathroom and must figure out how to escape a sadistic killer.",
                date: "2004-10-29",
                rating: 7.6,
                chapters: [],
            }
        ]
    },
    // Temática: Familia
    {
        title: "Familia",
        list: [
            {
                _id: "16",
                image: "https://example.com/image16.jpg",
                type: "film",
                title: "Coco",
                description: "A young boy embarks on a journey to the Land of the Dead to uncover the truth about his family's past.",
                date: "2017-11-22",
                rating: 8.4,
                chapters: [],
            },
            {
                _id: "17",
                image: "https://example.com/image17.jpg",
                type: "serie",
                title: "Modern Family",
                description: "An ensemble comedy that follows the diverse Pritchett-Dunphy-Tucker family.",
                date: "2009-09-23",
                rating: 8.5,
                chapters: [],
            },
            {
                _id: "18",
                image: "https://example.com/image18.jpg",
                type: "film",
                title: "The Lion King",
                description: "A young lion prince flees his kingdom after the murder of his father, only to learn the true meaning of responsibility and bravery.",
                date: "1994-06-15",
                rating: 8.5,
                chapters: [],
            },
            {
                _id: "19",
                image: "https://example.com/image19.jpg",
                type: "film",
                title: "The Incredibles",
                description: "A family of superheroes must come together to save the world from a dangerous enemy.",
                date: "2004-11-05",
                rating: 8.0,
                chapters: [],
            },
            {
                _id: "20",
                image: "https://example.com/image20.jpg",
                type: "film",
                title: "Finding Nemo",
                description: "After his son is captured in the Great Barrier Reef, a timid clownfish sets out on a journey to bring him home.",
                date: "2003-05-30",
                rating: 8.1,
                chapters: [],
            },
            {
                _id: "21",
                image: "https://example.com/image21.jpg",
                type: "film",
                title: "Paddington",
                description: "A young bear from Peru arrives in London looking for a new home and a family to call his own.",
                date: "2014-11-28",
                rating: 7.8,
                chapters: [],
            },
            {
                _id: "22",
                image: "https://example.com/image22.jpg",
                type: "film",
                title: "Frozen",
                description: "A young woman with ice powers accidentally plunges her kingdom into eternal winter and must go on a journey to restore peace.",
                date: "2013-11-27",
                rating: 7.4,
                chapters: [],
            },
            {
                _id: "23",
                image: "https://example.com/image23.jpg",
                type: "film",
                title: "Shrek",
                description: "An ogre reluctantly teams up with a loudmouthed donkey to rescue a princess and reclaim his swamp.",
                date: "2001-05-18",
                rating: 7.9,
                chapters: [],
            },
            {
                _id: "24",
                image: "https://example.com/image24.jpg",
                type: "film",
                title: "Toy Story",
                description: "A group of toys come to life when their owner is away, navigating friendships and rivalries.",
                date: "1995-11-22",
                rating: 8.3,
                chapters: [],
            },
            {
                _id: "25",
                image: "https://example.com/image25.jpg",
                type: "film",
                title: "Moana",
                description: "A daring young girl sets out on a seafaring journey to save her island from a destructive force.",
                date: "2016-11-23",
                rating: 7.6,
                chapters: [],
            },
            {
                _id: "26",
                image: "https://example.com/image26.jpg",
                type: "serie",
                title: "Full House",
                description: "A widowed father enlists the help of his brother-in-law and best friend to raise his three daughters.",
                date: "1987-09-22",
                rating: 6.7,
                chapters: [],
            },
            {
                _id: "27",
                image: "https://example.com/image27.jpg",
                type: "film",
                title: "The Parent Trap",
                description: "Two identical twin sisters separated at birth are reunited at summer camp and plot to bring their divorced parents back together.",
                date: "1998-07-29",
                rating: 6.6,
                chapters: [],
            },
            {
                _id: "28",
                image: "https://example.com/image28.jpg",
                type: "film",
                title: "Mary Poppins",
                description: "A magical nanny helps a dysfunctional family rediscover the joy and magic of childhood.",
                date: "1964-08-27",
                rating: 7.8,
                chapters: [],
            },
            {
                _id: "29",
                image: "https://example.com/image29.jpg",
                type: "film",
                title: "Matilda",
                description: "A young girl with extraordinary powers must overcome her cruel family and oppressive school principal.",
                date: "1996-08-02",
                rating: 6.9,
                chapters: [],
            },
            {
                _id: "30",
                image: "https://example.com/image30.jpg",
                type: "film",
                title: "Home Alone",
                description: "An eight-year-old boy is left behind when his family goes on vacation and must protect his home from burglars.",
                date: "1990-11-16",
                rating: 7.6,
                chapters: [],
            }
        ]
    }
]
